[workspace]
members = [
    "simd-minimizers",
    "simd-minimizers-bench",
]
resolver = "2"

[profile.release]
lto = "thin"
incremental = true
debug = true

[workspace.dependencies]
packed-seq = { version = "0.1.0", git = "https://github.com/rust-seq/packed-seq" }
